name = "SpeedyWeather"
uuid = "9e226e20-d153-4fed-8a5b-493def4f21a9"
authors = ["Milan Kl√∂wer and SpeedyWeather contributors"]
version = "0.12.1"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AssociatedLegendrePolynomials = "2119f1ac-fb78-50f5-8cc0-dda848ebdb19"
BitInformation = "de688a37-743e-4ac2-a6f0-bd62414d1aa7"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GenericFFT = "a8297547-1b15-4a5a-a998-a2ac5f1cef28"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
SpeedyWeatherCUDAExt = "CUDA"
SpeedyWeatherEnzymeExt = "Enzyme"
SpeedyWeatherFiniteDifferencesExt = "FiniteDifferences"
SpeedyWeatherGeoMakieExt = "GeoMakie"
SpeedyWeatherJLArraysExt = "JLArrays"
SpeedyWeatherMakieExt = "Makie"

[compat]
AbstractFFTs = "1"
Adapt = "3, 4"
AssociatedLegendrePolynomials = "1"
BitInformation = "0.6"
CUDA = "4, 5"
CodecZlib = "0.7"
Dates = "1.10"
DocStringExtensions = "0.9"
FFTW = "1"
FastGaussQuadrature = "0.4, 0.5, 1"
FiniteDifferences = "0.12"
GPUArrays = "11"
GenericFFT = "0.1"
GeoMakie = "0.7.6"
JLArrays = "0.1.4, 0.2"
JLD2 = "0.4, 0.5"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
Makie = "0.20, 0.21"
NCDatasets = "0.12, 0.13, 0.14"
Primes = "0.5"
Printf = "1.10"
ProgressMeter = "1.7"
Random = "1.10"
Statistics = "1.10"
TOML = "1"
UnicodePlots = "3.3"
julia = "1.10"
