[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CairoMakie = "0.12"
Documenter = "0.26, 0.27, 1"
GeoMakie = "0.7.6"
NCDatasets = "0.12, 0.13, 0.14"
UnicodePlots = "3"
